CREATE DATABASE IF NOT EXISTS calculatrice;

USE calculatrice;

CREATE TABLE IF NOT EXISTS calcul (
    id INT AUTO_INCREMENT PRIMARY KEY,
    expression VARCHAR(255) NOT NULL,
    resultat DOUBLE NOT NULL,
    horodatage DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);